services:
  
  node:
    image: node:22
    restart: 'always'
    working_dir: /src/app/
    volumes:
      - ./frontend:/src/app/
    ports:
      - 8080:8080
    command: "npm run dev"

  nginx:
    image: nginx:latest
    restart: 'always'
    volumes:
      - ./docker/nginx/conf/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./frontend/dist:/var/www/html/public
      - /root/.acme.sh/ssl/:/etc/nginx/certs
#      - ./docker/nginx/conf/allowed.users.dev:/etc/nginx/allowed.users
    ports:
      - "443:443"